name = "superstreamer-stitcher"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
send_metrics = false

[vars]
SERVERLESS = "true"
PORT = "0"
HOST = "0.0.0.0"
REDIS_HOST = "redis"
REDIS_PORT = "0000"
PUBLIC_S3_ENDPOINT = "https://cdn.superstreamer.xyz"
PUBLIC_STITCHER_ENDPOINT = "https://stitcher.superstreamer.xyz"

[[kv_namespaces]]
binding = "sessions"
id = "0385981fe1df474ca3648f625e18ba33"